### ISSUE TITLE
Cors Errors

### ISSUE THREAD

**Issue by Galileon-venta** [shlinkio/shlink#987] opened 2021-01-25 12:27 UTC
#### How Shlink is set-up

* Shlink Version: 2.5.2
* PHP Version: 7.4.14
* How do you serve Shlink: Self-hosted IIS
* Database engine used: SQLite

#### Summary

I tried self hosting api + client but the client is throwing cors errors.
Client is installed under domain.com/link
Api is installed under link.domain.com

#### Current behavior

Access to XMLHttpRequest at 'https://link.domain.com/rest/v2/health' from origin 'https://domain.com' has been blocked by CORS policy: Request header field x-api-key is not allowed by Access-Control-Allow-Headers in preflight response.

#### Expected behavior

Client works ?!

#### How to reproduce

IDK, setup the Domain Subdomain Combination like I did?

**Comment by Galileon-venta** [comment] 2021-01-25 12:29
Just tried the https://app.shlink.io version as well... Cors D:

**Comment by acelaya** [comment] 2021-01-25 13:59
That means that something in between is messing the request/response headers. Maybe IIS.

What Shlink does is taking the value sent in `Access-Control-Request-Headers` header, and return it in `Access-Control-Allow-Headers` in the response. One of the two is wrong.

You can verify which of the two is by running this:

`curl -X OPTIONS https://acel.me/rest/v2/health -H  "accept: application/json" -H "origin: foo" -H "Access-Control-Request-Headers: content-type,x-api-key" -I`

Change `https://acel.me` (which is my own Shlink instance) by your server URL.

It should print something like this, where you can see the `Access-Control-Allow-Headers` header includes `x-api-key`.

![image](https://user-images.githubusercontent.com/2719332/105715189-94cbb300-5f1d-11eb-9f50-e9bf9f83804f.png)

Try that and let me know the result to continue from there.

**Comment by Galileon-venta** [comment] 2021-01-25 14:55
So I did a tweak to the index.php to dump the Headers incoming and tried from Postman:

...
["X-Original-Url"]=>
string(15) "/rest/v2/health"
["Postman-Token"]=>
string(36) "abbcaf5d-30a9-4651-937e-0cda6108ef6f"
["Access-Control-Request-Headers"]=>
string(22) "content-type,x-api-key"
["Origin"]=>
string(3) "foo"
["User-Agent"]=>
string(21) "PostmanRuntime/7.26.8"
["Host"]=>
string(14) "link.venta.one"
...


I can see the headers comming into the php script;
So next Step I created a different file that emits custom headers:
`<?php
header("X-ABC: DEFG");
header("ABC: DEFG");`

with the following result in Postman:
![image](https://user-images.githubusercontent.com/48894231/105721610-0fe49780-5f25-11eb-8348-93d27fcad38a.png)

So in my opinion IIS isn't the thing...

**Comment by acelaya** [comment] 2021-01-25 14:58
Can you try the curl command I shared?

**Comment by Galileon-venta** [comment] 2021-01-25 15:18
Sure: 
Here is the Response:
![image](https://user-images.githubusercontent.com/48894231/105725126-de6dcb00-5f28-11eb-92d9-0c62df9768c2.png)

**Comment by Galileon-venta** [comment] 2021-01-25 15:25
Ouh thats interesting:

![image](https://user-images.githubusercontent.com/48894231/105725962-d95d4b80-5f29-11eb-834b-48817b4503bf.png)

This is from Networking Tab in Opera

**Comment by Galileon-venta** [comment] 2021-01-25 15:29
I know IIS is not officialy supported so I appreciate your help... For now I did this to the Middleware File:
![image](https://user-images.githubusercontent.com/48894231/105726290-32c57a80-5f2a-11eb-9387-738293e8cb56.png)
which seems to fix the double header; Interestingly enough that curl just showed one  ¯\_(ツ)_/¯

**Comment by acelaya** [comment] 2021-01-25 16:01
Does removing that duplicated header solve the error?

**Comment by Galileon-venta** [comment] 2021-01-25 16:09
Yep should I close the Issue?

**Comment by acelaya** [comment] 2021-01-25 16:20
Yep, let's close it. I'll do some more tests though (I haven't tried Opera) to see if I can come up with the root cause.

Maybe Shlink is actually generating the header twice, but Opera is the only one complaining in that case. CORS is hard, haha.

**Closed by acelaya** 2021-01-25 16:20 UTC
Labels: bug
