### ISSUE TITLE
Error on installation using php 7.4.4

### ISSUE THREAD

**Issue by elaur** [shlinkio/shlink#768] opened 2020-05-14 20:50 UTC
#### How Shlink is set-up

* Shlink Version: 2.2.1
* PHP Version: 7.4.4
* How do you serve Shlink: Self-hosted OpenLiteSpeed
* Database engine used: MariaDB
* OS: Debian 10

#### Summary

sudo -u lsadm /usr/local/lsws/lsphp74/bin/lsphp ./install 
PHP Fatal error:  strict_types declaration must be the very first statement in the script in /usr/local/lsws/mydomain.cc/html/bin/install on line 3

Fatal error: strict_types declaration must be the very first statement in the script in /usr/local/lsws/mydomain.cc/html/bin/install on line 3

Any solutions to fix it?

**Comment by acelaya** [comment] 2020-05-14 21:35
I'm not sure what this lsphp thing is, but it looks like it is performing some kind of code style check.

I would recommend you running Shlink with a regular PHP binary. That will solve the problem.

**Comment by acelaya** [comment] 2020-05-15 07:56
Hey @elaur 

I have done a bit of research, and it looks like this error could be caused by the fact that this is a CLI script and stats with the shebang.

Could you try removing the `#!/usr/bin/env php` like at the beginning of the install script and see if it helps?

**Comment by elaur** [comment] 2020-05-15 15:43
### Hmm, got this

sudo -u lsadm /usr/local/lsws/lsphp74/bin/lsphp ./install

 Welcome to Shlink!!
 This tool will guide you through the installation process.

DATABASE
========

 Select database type [MySQL]:
  [0] MySQL
  [1] MariaDB
  [2] PostgreSQL
  [3] MicrosoftSQL
  [4] SQLite
 > PHP Warning:  Use of undefined constant STDIN - assumed 'STDIN' (this will throw an Error in a future version of PHP) in /usr/local/lsws/mywebsite.cc/html/vendor/symfony/console/Helper/QuestionHelper.php on line 107

Warning: Use of undefined constant STDIN - assumed 'STDIN' (this will throw an Error in a future version of PHP) in /usr/local/lsws/mywebsite.cc/html/vendor/symfony/console/Helper/QuestionHelper.php on line 107
PHP Warning:  feof() expects parameter 1 to be resource, string given in /usr/local/lsws/mywebsite.cc/html/vendor/symfony/console/Helper/QuestionHelper.php on line 254

Warning: feof() expects parameter 1 to be resource, string given in /usr/local/lsws/mywebsite.cc/html/vendor/symfony/console/Helper/QuestionHelper.php on line 254
PHP Warning:  fread() expects parameter 1 to be resource, string given in /usr/local/lsws/mywebsite.cc/html/vendor/symfony/console/Helper/QuestionHelper.php on line 255

Warning: fread() expects parameter 1 to be resource, string given in /usr/local/lsws/mywebsite.cc/html/vendor/symfony/console/Helper/QuestionHelper.php on line 255
PHP Fatal error:  Uncaught TypeError: Return value of Shlinkio\Shlink\Installer\Config\Option\Database\DatabaseUserConfigOption::askRequired() must be of the type string, null returned in /usr/local/lsws/mywebsite.cc/html/vendor/shlinkio/shlink-installer/src/Util/AskUtilsTrait.php:20
Stack trace:
#0 /usr/local/lsws/mywebsite.cc/html/vendor/shlinkio/shlink-installer/src/Config/Option/Database/DatabaseUserConfigOption.php(22): Shlinkio\Shlink\Installer\Config\Option\Database\DatabaseUserConfigOption->askRequired()
#1 /usr/local/lsws/mywebsite.cc/html/vendor/shlinkio/shlink-installer/src/Config/ConfigGenerator.php(58): Shlinkio\Shlink\Installer\Config\Option\Database\DatabaseUserConfigOption->ask()
#2 /usr/local/lsws/mywebsite.cc/html/vendor/shlinkio/shlink-installer/src/Command/InstallCommand.php(77): Shlinkio\Shlink\Installer\Config\ConfigGenerator->generateConfigInteractively()
#3 /usr/local/lsws/mywebsite.cc/html/vendor/symfony/console/Command/Command.php(255): Shlinkio\Shlink\Installer\Command\InstallCommand->execute()
#4 /usr/local/lsws/mywebsite.cc/htm in /usr/local/lsws/mywebsite.cc/html/vendor/shlinkio/shlink-installer/src/Util/AskUtilsTrait.php on line 20

Fatal error: Uncaught TypeError: Return value of Shlinkio\Shlink\Installer\Config\Option\Database\DatabaseUserConfigOption::askRequired() must be of the type string, null returned in /usr/local/lsws/mywebsite.cc/html/vendor/shlinkio/shlink-installer/src/Util/AskUtilsTrait.php:20
Stack trace:
#0 /usr/local/lsws/mywebsite.cc/html/vendor/shlinkio/shlink-installer/src/Config/Option/Database/DatabaseUserConfigOption.php(22): Shlinkio\Shlink\Installer\Config\Option\Database\DatabaseUserConfigOption->askRequired()
#1 /usr/local/lsws/mywebsite.cc/html/vendor/shlinkio/shlink-installer/src/Config/ConfigGenerator.php(58): Shlinkio\Shlink\Installer\Config\Option\Database\DatabaseUserConfigOption->ask()
#2 /usr/local/lsws/mywebsite.cc/html/vendor/shlinkio/shlink-installer/src/Command/InstallCommand.php(77): Shlinkio\Shlink\Installer\Config\ConfigGenerator->generateConfigInteractively()
#3 /usr/local/lsws/mywebsite.cc/html/vendor/symfony/console/Command/Command.php(255): Shlinkio\Shlink\Installer\Command\InstallCommand->execute()
#4 /usr/local/lsws/mywebsite.cc/htm in /usr/local/lsws/mywebsite.cc/html/vendor/shlinkio/shlink-installer/src/Util/AskUtilsTrait.php on line 20

**Comment by acelaya** [comment] 2020-05-15 16:02
It's hard to say, but it looks like everything is related with the PHP variation you are using.

I would recommend using a regular PHP distribution, as some of these errors are happening on third party code that I will not be able to change.

I will close this for now, and consider supporting lite speed PHP in the future.

**Closed by acelaya** 2020-05-15 16:02 UTC
Labels: question
