### ISSUE TITLE
Human-friendly automatically generated slugs/short codes

### ISSUE THREAD

**Issue by Plausible0Bug** [shlinkio/shlink#475] opened 2019-08-23 22:16 UTC
I noticed one feature that can be useful is to generate short URLs easy to read and memorize.

Maybe we can have pluggable slug generators? Maybe borrow some ideas from https://github.com/moby/moby/blob/master/pkg/namesgenerator/names-generator.go ?

Great project, by the way.

**Comment by acelaya** [comment] 2019-08-24 06:37
Hey @Plausible0Bug.

Thanks for the kind words and for taking the time to contribute ideas to the project.

This feature would be something nice to have, but I don't see a huge benefit compared with the maintenance cost.

I'm not going to close the issue, bit I cannot promise to have it done soon.

**Comment by Plausible0Bug** [comment] 2019-09-05 00:45
Hi,

Thanks for the promptly reply, I'll try to see if I can contribute code wise but please bear with me if I make mistakes, I'm totally new to PHP world.

I would like to further explain my intention: When copy&paste is not immediately possible we need to pass the short URL by reading it out, it had caused some trouble thanks to the following implementation factors:

1. The short URL slug is case sensitive.
2. There are mixed usage of `I` and `l`.
3. When the slug become longer than 6 characters, it can be very hard to pronounce.

I noticed hastebin has a relatively welcomed implementation named phonetic key generator, the implementation(in JavaScript) seemed very simple:
https://github.com/seejohnrun/haste-server/blob/master/lib/key_generators/phonetic.js

I would like to see(or contribute) something similar, if possible.

**Comment by acelaya** [comment] 2019-09-05 06:21
I can understand this is important for you, but it's not really something people usually look for on a URL shortener.

There are several tasks with a higher priority that need to be tackled first. You can see the planned work and tasks here https://github.com/shlinkio/shlink/milestones.

As you can see, the work for next 3 versions is already planned, and there's probably going to be some patches in between, plus some work in other repositories from the project.

You can see the overall project work in progress here 

What I'm trying to say is that I don't think I can really focus on this feature before next year (being generous), either by doing it myself or by reviewing PR from contributors.

I'm really sorry I cannot give you better news, honestly.

For now, I would recommend using custom slugs (the regular ones, where you decide what's the value).

**Comment by acelaya** [comment] 2019-09-19 05:21
I'm afraid I have to close this.

Several new feature requests with a higher benefit for the project have been created in the past days, and some cleanup is required.

**Closed by acelaya** 2019-09-19 05:21 UTC
Labels: feature

**Comment by ron-majumdar** [comment] 2020-06-03 17:32
@acelaya - not sure why you do not see the use of a slug unimportant. I am evaluating several URL Shortening Open Source projects at the moment and I really like shlink. But there are 2 factors that "make or break" the decision to go with shlink.

Can we scale this ?
Can we customize this ?

I have 1000's of urls that I would like to use and move into shlink. Most of the URLs are customized slugs and we have a naming convention for the slugs so that people can get to it by just thinking logically and using the naming convention if they have not saved the url. A machine generate code cannot be remembered.

I am also not sure why you think implementing this is difficult!
- all you need to do is to allow the code to be changed to the slug
- or add another column for the slug if you want to maintain the unique code
the code and the slug are candidate keys and MUST be unique.

I am not even sure why this is even a debate and the issue is closed with a refusal to implement this feature when the feature listed on the site clearly says:
https://shlink.io/features/
"Custom slugs
Personalize your short URLs by using custom slugs. This will help you easily identify campaigns."


Support @Plausible0Bug on this.

**Comment by acelaya** [comment] 2020-06-03 17:39
The feature that was being under discussion here was not the ability to provide custom slugs. That's supported by shlink.

The request was to make shlink generate human-friendly slugs by itself, without you having to provide anything. Something similar to what docker does when generating temp container names.

**Comment by xoxfaby** [comment] 2025-08-02 20:48
would you reconsider this? I would hope that pointing the logic for generating the slug at a different function shouldn't be very hard, so that the logic can be customized. At that point, returning simply english words as slugs creates shortened url's that are very easy to both memorize and type out manually.
