### ISSUE TITLE
Daily GeoIP Database Download Limit Reached

### ISSUE THREAD

**Issue by michabbb** [shlinkio/shlink#1426] opened 2022-04-20 22:20 UTC
hi,

i got an email from geoip and when I check the download history, it looks strange to me:

![image](https://user-images.githubusercontent.com/3524595/164334285-760e7a1b-e989-4569-ac88-0e85158ad448.png)

so, besides the question my shrink is trying to download that often, I am more interested in "how can I disable the geoip stuff in general?" because I don´t really need it. i just made the setup to see if that brings any valuable info for me, but it doesn't.

thanks!

**Comment by acelaya** [comment] 2022-04-21 05:14
Yeah, this is something I need to investigate, because the same happened to me.

> how can I disable the geoip stuff in general?

It depends on the Shlink version you are using. Assuming it's 3.x, just don't provide the GeoLite2 key, and it will stop geolocating visits.

**Comment by acelaya** [comment] 2022-04-27 14:15
Just noticed @michabbb experienced this with version `GeoLite2-City_20220419.tar.gz`, which for me has worked fine, so maybe that means it has nothing to do with the files themeselves.

**Comment by michabbb** [comment] 2022-04-27 15:12
removing the key from my docker-compose file, does not do the trick, the app still tries to download the database:

```
Next Shlinkio\Shlink\CLI\Exception\GeolocationDbUpdateFailedException: An error occurred while updating geolocation database, and an older version could not be found. in /etc/shlink/module/CLI/src/Exception/GeolocationDbUpdateFailedException.php:30
Stack trace:
#0 /etc/shlink/module/CLI/src/Util/GeolocationDbUpdater.php(77): Shlinkio\Shlink\CLI\Exception\GeolocationDbUpdateFailedException::withoutOlderDb(Object(Shlinkio\Shlink\IpGeolocation\Exception\DbUpdateException))
#1 /etc/shlink/module/CLI/src/Util/GeolocationDbUpdater.php(53): Shlinkio\Shlink\CLI\Util\GeolocationDbUpdater->downloadNewDb(false, Object(Closure), NULL)
#2 /etc/shlink/module/CLI/src/Util/GeolocationDbUpdater.php(41): Shlinkio\Shlink\CLI\Util\GeolocationDbUpdater->downloadIfNeeded(Object(Closure), NULL)
#3 /etc/shlink/module/Core/src/EventDispatcher/LocateVisit.php(69): Shlinkio\Shlink\CLI\Util\GeolocationDbUpdater->checkDbUpdate(Object(Closure))
#4 /etc/shlink/module/Core/src/EventDispatcher/LocateVisit.php(57): Shlinkio\Shlink\Core\EventDispatcher\LocateVisit->downloadOrUpdateGeoLiteDb('322241')
#5 /etc/shlink/module/Core/src/EventDispatcher/CloseDbConnectionEventListener.php(26): Shlinkio\Shlink\Core\EventDispatcher\LocateVisit->__invoke(Object(Shlinkio\Shlink\Core\EventDispatcher\Event\UrlVisited))
#6 /etc/shlink/vendor/mezzio/mezzio-swoole/src/Task/ServiceBasedTask.php(55): Shlinkio\Shlink\Core\EventDispatcher\CloseDbConnectionEventListener->__invoke(Object(Shlinkio\Shlink\Core\EventDispatcher\Event\UrlVisited))
#7 /etc/shlink/vendor/mezzio/mezzio-swoole/src/Task/TaskInvokerListener.php(51): Mezzio\Swoole\Task\ServiceBasedTask->__invoke(Object(Laminas\ServiceManager\ServiceManager))
#8 /etc/shlink/vendor/mezzio/mezzio-swoole/src/Event/EventDispatcher.php(41): Mezzio\Swoole\Task\TaskInvokerListener->__invoke(Object(Mezzio\Swoole\Event\TaskEvent))
#9 /etc/shlink/vendor/mezzio/mezzio-swoole/src/SwooleRequestHandlerRunner.php(192): Mezzio\Swoole\Event\EventDispatcher->dispatch(Object(Mezzio\Swoole\Event\TaskEvent))
#10 [internal function]: Mezzio\Swoole\SwooleRequestHandlerRunner->onTask(Object(Swoole\Http\Server), 4498, 2, Object(Mezzio\Swoole\Task\ServiceBasedTask))
#11 /etc/shlink/vendor/mezzio/mezzio-swoole/src/SwooleRequestHandlerRunner.php(86): Swoole\Server->start()
#12 /etc/shlink/vendor/mezzio/mezzio/src/Application.php(82): Mezzio\Swoole\SwooleRequestHandlerRunner->run()
#13 /etc/shlink/vendor/mezzio/mezzio-swoole/src/Command/StartCommand.php(122): Mezzio\Application->run()
#14 /etc/shlink/vendor/symfony/console/Command/Command.php(256): Mezzio\Swoole\Command\StartCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /etc/shlink/vendor/symfony/console/Application.php(989): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /etc/shlink/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand(Object(Mezzio\Swoole\Command\StartCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /etc/shlink/vendor/symfony/console/Application.php(166): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /etc/shlink/vendor/laminas/laminas-cli/bin/laminas(30): Symfony\Component\Console\Application->run()
#19 {main}
[2022-04-27T14:50:10.733601+00:00] [cb9b807b-d93a-4122-a328-690bd064319a] Shlink.NOTICE - Task 4498 has finished
[2022-04-27T14:50:39.455532+00:00] [91fb3590-a7ed-417a-827c-7c280908a613] Access.INFO - 127.0.0.1 - - "GET /rest/v2/health HTTP/1.1" 200 120
[2022-04-27T14:51:05.213043+00:00] [NULL] Shlink.NOTICE - Starting work on task 199 using: {"handler":"Shlinkio\\Shlink\\Core\\EventDispatcher\\LocateVisit","arguments":[{"visitId":"322242"}]}
[2022-04-27T14:51:05.213717+00:00] [0aec7337-137a-40ea-b36a-797465fc1816] Access.ERROR - 23.88.41.31 - - "GET / HTTP/1.1" 404 979
[2022-04-27T14:51:05.215986+00:00] [NULL] Shlink.NOTICE - Downloading GeoLite2 database...[2022-04-27T14:51:05.427642+00:00] [NULL] Shlink.ERROR - GeoLite2 database download failed. It is not possible to locate visit with id 322242.
GuzzleHttp\Exception\ClientException: Client error: `GET https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=G4Lm0C60yJsnkdPi&suffix=tar.gz` resulted in a `401 Unauthorized` response:
Invalid license key
```

I am running version v2.6.2 with docker.
please let me know how to disable the geoip download. 

thanks!

**Comment by acelaya** [comment] 2022-04-28 05:58
@michabbb v2.6 is pretty old. If you update at least to v2.7, that one introduced more granularity on how to handle visits tracking.

See https://shlink.io/documentation/tracking-visits/#disable-tracking and https://shlink.io/documentation/environment-variables/#visits-tracking

**Comment by michabbb** [comment] 2022-04-28 08:06
@acelaya thanks will do, but can I just change the docker image or is there a migration path I have to go? because I don't know what has changed in the database since then.

**Comment by Lavode** [comment] 2022-04-28 08:12
> Could any of you check your download history (once logged in maxmind.com, the left menu has a "Download history" option) to see if the versions match?

For me it happened with the `GeoLite2-City_20220419.tar.gz` file, first request was `2022-04-26 17:17:15`, last one (when we hit the 2k daily download cap) `2022-04-26 22:03:15`

**Comment by acelaya** [comment] 2022-04-28 09:15
> @acelaya thanks will do, but can I just change the docker image or is there a migration path I have to go? because I don't know what has changed in the database since then. 

You can just update the image and it will take care of updating the database if needed.

**Comment by acelaya** [comment] 2022-04-28 09:16
> For me it happened with the `GeoLite2-City_20220419.tar.gz` file, first request was `2022-04-26 17:17:15`, last one (when we hit the 2k daily download cap and were rate-limited by their API) `2022-04-26 22:03:15`

Can you try restarting Shlink?

**Comment by acelaya** [comment] 2022-04-28 09:39
> > > For me it happened with the `GeoLite2-City_20220419.tar.gz` file, first request was `2022-04-26 17:17:15`, last one (when we hit the 2k daily download cap and were rate-limited by their API) `2022-04-26 22:03:15`
> > 
> > Can you try restarting Shlink?
> 
> Yea, that seems to have helped (now that the rate limiting on the API has expired).
> 
> Based on Maxmind's backend there was now one download of `GeoLite2-City_20220426.tar.gz`, and subsequent visits to Shlink seem not to trigger any more downloads.

I experienced the same. I have to investigate the reason.

**Comment by michabbb** [comment] 2022-04-28 10:22
> You can just update the image and it will take care of updating the database if needed.

@acelaya good2know, okay, will try - 🙈 🤞

**Comment by acelaya** [comment] 2022-05-27 07:43
Could you guys tell me in what GeoLite2 version did you start expriencing this? I have the suspicion this might have been caused by some wrong metadata in one specific version, which got resolved once Shlink was restarted.

**Comment by Lavode** [comment] 2022-05-27 07:51
`GeoLite2-City_20220419.tar.gz`

**Comment by acelaya** [comment] 2022-06-04 08:30
I'm afraid I'm not being able to reproduce this anymore. Something clearly happened at some point with this, but it's very unclear to me, and seems to get fixed by restarting Shlink and never happens again.

I'm going to close this for now, but feel free to post comments if new information is found.

**Closed by acelaya** 2022-06-04 08:30 UTC
Labels: bug, question
