### ISSUE TITLE
Default 404 page is still used when NOT_FOUND_REDIRECT_TO is provided

### ISSUE THREAD

**Issue by Plausible0Bug** [shlinkio/shlink#455] opened 2019-08-10 19:10 UTC
The redirect to url provided in NOT_FOUND_REDIRECT_TO environment variable will happen if user goes to doma.in/1234 and `1234` is not a valid shortend link, but user will still see default 404 page if they visit doma.in

**Comment by acelaya** [comment] 2019-08-10 19:45
Yes, that's a known issue. In fact it was a sort of intended behavior, but so many people is reporting it as an issue, so I'm going to change it.

You can watch these two issues. I'm closing this for now.

* https://github.com/shlinkio/shlink/issues/419

**Closed by acelaya** 2019-08-10 19:45 UTC
