### ISSUE TITLE
Updates fail from 3.4.0 -> 3.5.4/3.5.0

### ISSUE THREAD

**Issue by theofficialgman** [shlinkio/shlink#2186] opened 2024-09-03 15:03 UTC
### Shlink version

3.5.4/3.5.0

### PHP version

8.1.2

### How do you serve Shlink

Self-hosted nginx

### Database engine

MySQL

### Database version

8.0.39

### Current behavior

attempting to update from 3.4.0 to 3.5.4 (or 3.5.0) appears to go without error. However, after starting the nginx server all calls to shlink fail (eg: https://app.shlink.io errors like the server is offline).

### Expected behavior

I expect that shlink upgrades do not fail.

### Minimum steps to reproduce

untested:
- install 3.4.0 on self hosted nginx with mysql on ubuntu jammy 22.04 and configure and capture some clicks
- stop nginx
- upgrade to 3.5.4
- start nginx
- observe that the server appears to still not respond

**Comment by acelaya** [comment] 2024-09-03 15:33
Closing as not reproducible for now, until some "tested" steps have been provided.

**Closed by acelaya** 2024-09-03 15:33 UTC
Labels: bug

**Comment by theofficialgman** [comment] 2024-09-03 15:47
@acelaya here are some logs for your debugging purposes. all logs produced after updating

```
2024/09/03 15:46:55 [error] 10839#10839: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Shlinkio\Shlink\Config\parseEnvVar(), 0 passed in /var/www/shlink/vendor/shlinkio/shlink-config/functions/functions.php on line 83 and exactly 1 expected in /var/www/shlink/vendor/shlinkio/shlink-config/functions/functions.php:46
Stack trace:
#0 /var/www/shlink/vendor/shlinkio/shlink-config/functions/functions.php(83): Shlinkio\Shlink\Config\parseEnvVar()
#1 /var/www/shlink/config/autoload/swoole.global.php(26): Shlinkio\Shlink\Config\getOpenswooleConfigFromEnv()
#2 /var/www/shlink/config/autoload/swoole.global.php(34): Laminas\ConfigAggregator\PhpFileProvider::{closure}()
#3 /var/www/shlink/vendor/laminas/laminas-config-aggregator/src/PhpFileProvider.php(29): include('...')
#4 /var/www/shlink/vendor/laminas/laminas-config-aggregator/src/ConfigAggregator.php(238): Laminas\ConfigAggregator\PhpFileProvider->__invoke()
#5 /var/www/shlink/vendor/laminas/laminas-config-aggregator/src/ConfigAggregator.php(82): Lami" while reading response header from upstream, client: 2001:8a0:f9c2:6a00:2ecf:67ff:fe2f:e83e, server: analytics.pi-apps.io, request: "GET /pi-apps-install-BetterChromium/track HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.1-fpm.sock:", host: "analytics.pi-apps.io"
2024/09/03 15:46:57 [error] 10839#10839: *3 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Shlinkio\Shlink\Config\parseEnvVar(), 0 passed in /var/www/shlink/vendor/shlinkio/shlink-config/functions/functions.php on line 83 and exactly 1 expected in /var/www/shlink/vendor/shlinkio/shlink-config/functions/functions.php:46
Stack trace:
#0 /var/www/shlink/vendor/shlinkio/shlink-config/functions/functions.php(83): Shlinkio\Shlink\Config\parseEnvVar()
#1 /var/www/shlink/config/autoload/swoole.global.php(26): Shlinkio\Shlink\Config\getOpenswooleConfigFromEnv()
#2 /var/www/shlink/config/autoload/swoole.global.php(34): Laminas\ConfigAggregator\PhpFileProvider::{closure}()
#3 /var/www/shlink/vendor/laminas/laminas-config-aggregator/src/PhpFileProvider.php(29): include('...')
#4 /var/www/shlink/vendor/laminas/laminas-config-aggregator/src/ConfigAggregator.php(238): Laminas\ConfigAggregator\PhpFileProvider->__invoke()
#5 /var/www/shlink/vendor/laminas/laminas-config-aggregator/src/ConfigAggregator.php(82): Lami" while reading response header from upstream, client: 86.30.41.63, server: analytics.pi-apps.io, request: "GET /pi-apps-install-Box86/track HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.1-fpm.sock:", host: "analytics.pi-apps.io"
2024/09/03 15:46:58 [error] 10839#10839: *5 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Shlinkio\Shlink\Config\parseEnvVar(), 0 passed in /var/www/shlink/vendor/shlinkio/shlink-config/functions/functions.php on line 83 and exactly 1 expected in /var/www/shlink/vendor/shlinkio/shlink-config/functions/functions.php:46
Stack trace:
#0 /var/www/shlink/vendor/shlinkio/shlink-config/functions/functions.php(83): Shlinkio\Shlink\Config\parseEnvVar()
#1 /var/www/shlink/config/autoload/swoole.global.php(26): Shlinkio\Shlink\Config\getOpenswooleConfigFromEnv()
#2 /var/www/shlink/config/autoload/swoole.global.php(34): Laminas\ConfigAggregator\PhpFileProvider::{closure}()
#3 /var/www/shlink/vendor/laminas/laminas-config-aggregator/src/PhpFileProvider.php(29): include('...')
#4 /var/www/shlink/vendor/laminas/laminas-config-aggregator/src/ConfigAggregator.php(238): Laminas\ConfigAggregator\PhpFileProvider->__invoke()
#5 /var/www/shlink/vendor/laminas/laminas-config-aggregator/src/ConfigAggregator.php(82): Lami" while reading response header from upstream, client: 2001:8a0:f9c2:6a00:2ecf:67ff:fe2f:e83e, server: analytics.pi-apps.io, request: "GET /pi-apps-install-Chromium/track HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.1-fpm.sock:", host: "analytics.pi-apps.io"
```

**Comment by theofficialgman** [comment] 2024-09-03 15:59
@acelaya here are the step taken (over time) of the shlink server

- install 3.0.0 and configure as mentioned before
- time passes
- upgrade 3.0.0 -> 3.0.0 -> 3.1.2 -> 3.2.1 -> 3.3.0
- time passes
- upgrade 3.3.0 -> 3.3.2 -> 3.4.0
- errors logged as sent above after upgrading from 3.4.0 -> 3.5.0 or 3.5.4

Feel free to reduce the steps taken to the last upgrade. I will not because I have already provided the error in the log above.

**Comment by theofficialgman** [comment] 2024-09-03 16:11
@acelaya this issue was previously reported but closed and locked without good reason
https://github.com/shlinkio/shlink/issues/1718

so this issue is reproducible on a fresh 3.5.X install on php 8.1.2

**Comment by acelaya** [comment] 2024-09-03 16:32
> @acelaya this issue was previously reported but closed and locked without good reason #1718
> 
> so this issue is reproducible on a fresh 3.5.X install on php 8.1.2

The very first thing you can see there is a banner saying the issue was turned into a discussion. That's why it is locked.

![image](https://github.com/user-attachments/assets/c4812ec3-5c60-4eb1-9ed7-ab6394f506ae)

The comment marked as the discussion resolution explains the issue is a bug in PHP 8.1.2 https://github.com/shlinkio/shlink/discussions/1719#discussioncomment-5343177

**Comment by theofficialgman** [comment] 2024-09-03 16:52
`./bin/cli short-url:list` does work. just `https://app.shlink.io` doesn't work for showing urls.

**Comment by theofficialgman** [comment] 2024-09-03 17:12
updating 3.5.4 -> 3.6.4 does not resolve the issue.
I will need confirmation that this was a known bug and fixed in later versions before I proceed further.
