### ISSUE TITLE
Multiple links to the same URL

### ISSUE THREAD

**Issue by robwent** [shlinkio/shlink#188] opened 2018-09-09 17:41 UTC
This is something an old client wanted to do which wasn't possible with the link shortner they were using at the time. It doesn't seem possible with shlink either.

The use case is for testing the same link in different places. EG a newsletter, website content, website sidebar etc to see which one gets the most hits.

Looking at the db, the original_url column doesn't seem to have any unique constraints, but trying to create a second short link to the same url returns the first one generated.

I should note that I'm testing this using the web app not cli.

**Comment by acelaya** [comment] 2018-09-09 17:48
Yes, this should probably be considered a bug.

It was intended at the beginning, but the more I think it, the less it makes sense.

If the user wants to create several links to the same origin, it should be up to him. You could even want to apply different limits/slug/tags.

Maybe I consider some way to control it, but this should definitely be possible.

You have provided a lot of valuable feedback. Thanks again.

**Comment by acelaya** [comment] 2018-09-11 18:45
Closed via #192

**Closed** 2018-09-11 18:44 UTC
Labels: bug
