### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by figachek** [shlinkio/shlink#2147] opened 2024-07-02 09:43 UTC
Dear sirs,
after installing the latest shlink,
I generated short links, but when I click on them I get an error:
"Application error: a client-side exception has occurred (see the browser console for more information).".
<img width="1704" alt="Screenshot 2024-07-02 at 11 42 50" src="https://github.com/shlinkio/shlink/assets/20118454/81eef48b-3e68-4041-8024-05f008531299">
Please help

**Comment by acelaya** [comment] 2024-07-02 09:46
That doesn't look like Shlink at all. Probably an error in the page you are being redirected to.

**Comment by acelaya** [comment] 2024-07-02 10:38
Well, that's just not Shlink, I'm afraid 😅

Can you include the whole browser in the screenshot?

**Comment by acelaya** [comment] 2024-07-02 13:22
The most likely cause for this is a mismatch in the apps hosted in the same server, which means when you visit the URL which is supposedly pointing to your Shlink instance, it is in fact resolving a different service.

The error there is caused by a Next.js app. Next.js is a JavaScript full-stack framework. Shlink is written in PHP and has zero JavaScript for the browser.

**Closed by acelaya** 2024-07-02 13:22 UTC
