### ISSUE TITLE
Memory Limitation Bug with visit:process

### ISSUE THREAD

**Issue by tivyhosting** [shlinkio/shlink#307] opened 2018-12-05 23:29 UTC
When trying to run ```visit:process``` in the CLI I get the following error.

```
Allowed memory size of 268435456 bytes exhausted (tried to allocate 4096 bytes) in /shlink-1-13-1/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php on line 107
```

**Comment by tivyhosting** [comment] 2018-12-05 23:36
Increasing the php memory limit to 512mb fixes this

**Comment by acelaya** [comment] 2018-12-06 07:31
I would say it is still suffering from trying to handle big datasets.

This should have been mitigated with the latest change, but I'll keep investigating what else could be consuming that much memory.

**Comment by tivyhosting** [comment] 2018-12-06 07:39
I've updated to 1.15.0 and this issue still persists

**Comment by acelaya** [comment] 2019-02-17 11:20
Hi @tivyhosting. I'm trying to find where this memory leak is coming from.

Do you know how many visits does your system process every time you run the command? I just need an approximate value.

**Comment by tivyhosting** [comment] 2019-02-19 22:25
Unsure, but at the time I know that at least 96000 visits were unprocessed. My guess is somewhere in the 300-400k range.

**Comment by acelaya** [comment] 2019-02-20 00:13
Thanks @tivyhosting, that's really helpful.

Based on the huge amount of unprocessed visits and the kind of error, my guess is that the lower level database query is trying to load too many rows in memory 

I already made sure the ORM was not trying to map too many objects at the same time, but the raw query still loads all pending visits with no limit.

I think that making sure only smaller subsets are loaded at the same time should solve the issue, but I will run some benchmarks with big datasets in order to confirm.

Having the whole exception trace would also help confirm this theory, but I guess you never got to run the command with higher verbosity.

I will let you know once I have done some tests.

**Comment by acelaya** [comment] 2019-02-21 21:59
@tivyhosting  I have done several tests and I have managed to reproduce the issue when trying to process more than 400k pending visits.

My guess was right, the problem is that the query is trying to fetch the whole dataset at the same time.

I will try to provide a fix during this weekend and release the v1.16. This is the only issue left for that milestone.

**Comment by acelaya** [comment] 2019-02-23 09:03
@tivyhosting I'm about to merge the fix for this bug.

I have managed to make it load the visits to be located in blocks of 10k, which drastically reduces the memory peak, and it also makes it no longer exponential, so you can even process millions without affecting the memory ussage.

Also, as an interesting side effect, I have realized that the way located visits are then persisted could be improved, It is now done in blocks of 200, which makes the whole process waaaaaay faster. I have processed 200k visits in less than 5min, when it used to take about an hour with previous approach.

I will release the new version as soon as possible (once builds finish and such).

**Closed** 2019-02-23 09:09 UTC
Labels: bug

**Comment by acelaya** [comment] 2019-02-23 09:21
@tivyhosting v1.16.0 is already available https://github.com/shlinkio/shlink/releases/tag/v1.16.0

**Comment by tivyhosting** [comment] 2019-02-26 18:04
Noticed a almost 30 second constant spam of ignoring visit with no IP address. It seems like yes it does ignore these, but it doesn't seem to remove them from the to be processed queue. Maybe this is the reasoning for the memory leak?

Although after the update it does run fine, but doesn't spam the console with the IPs it has processed anymore?

https://i.imgur.com/NTdUBrI.png

**Comment by tivyhosting** [comment] 2019-02-26 18:06
Just piped it to a file, and its 550,000 results of "Ignored visit with no IP address" every time I run the command.

**Comment by acelaya** [comment] 2019-02-26 18:43
Nope, this is not the reason for the memory leak. That has been fixed, as explained some comments above.

This is a new issue intruded with the new implementation. It shouldn't have a big impact, but I agree it's quite annoying.

I will provide a fix for this in v1.16.1

**Comment by acelaya** [comment] 2019-02-26 19:14
I have to investigate a little bit further, but I'm now almost sure this is not a regression introduced with last version, but an issue which has always been there.

However, it has a very low impact so it can be unnoticed.

I will provide a fix either way.

**Comment by acelaya** [comment] 2019-02-26 20:09
@tivyhosting I just confirmed this has always been there. The message is only displayed when running the `visit:process` command in verbose mode (with `-v`, `-vv` or `-vvv`).

I think it is something that I wanted to fix at some point but got "lost". Now that there's a ticket tracking the issue I will remember to find a more elegant solution which prevents these visits to be processed over and over.
