### ISSUE TITLE
Unable to run docker image with external mariadb database after version 2.2 

### ISSUE THREAD

**Issue by nmm-cargoclix** [shlinkio/shlink#971] opened 2021-01-20 17:26 UTC
I had this error some time ago when 2.3.0 was released. Then i stuck the instance to the 2.2.2 image, which worked fine. Now i am trying fresh install, 2.5.0 on Kubernetes, and container fails with error: 

```
Creating fresh database if needed...
Updating database...

In ProcessHelper.php line 110:

  The command "'/usr/local/bin/php' 'vendor/doctrine/migrations/bin/doctrine-
  migrations.php' 'migrations:migrate' '--no-interaction'" failed.

  Exit Code: 1(General error)

  Working directory: /etc/shlink

  In MetadataStorageError.php line 13:

    The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue.

  migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--allow-no-migration] [--all-or-nothing [ALL-OR-NOTHING]] [--configuration CONFIGURATION] [--] [<version>]

db:migrate
```

Database is created, not sure what is missing there. 
Server is 10.3.23-MariaDB-log

**Comment by acelaya** [comment] 2021-01-20 19:25
Hey, thanks for reporting this.

Could you provide some reproducible steps? This seems pretty specific for a concrete combination.

How do you run the image? What are the env vars you provide?

**Comment by acelaya** [comment] 2021-01-20 19:39
One of the things introduced in v2.3 was a major version update for the library used to handle migrations, and I have found other people experiencing this with that same version.

One of the reasons reported by some people is the use of a dash on the name of the database. Could that be the case for you?

**Comment by nmm-cargoclix** [comment] 2021-01-20 21:36
Hi, yes, i also can confirm that, but it is another case. I tried with the dash in the database name and found that the the migration is failing, so i removed the dash. Now database is created, but above error persists. 
 
I am not sure what can i provide more from my setup.... here are the variables i set in my terraform managed azure kubernetes cluster: 

 spec {
        container {
          image = "shlinkio/shlink:2.5.0"
          name  = "env-dev-urlshortener"
          port {
            container_port = 8080
          }
          env {
            name  = "SHORT_DOMAIN_HOST"
            value = "link-dev.my-domain.com"
          }
          env {
            name  = "SHORT_DOMAIN_SCHEMA"
            value = "https"
          }
          env {
            name  = "DB_USER"
            value = "myuser"
          }
          env {
            name  = "DB_NAME"
            value = "devshlink"
          }
          env {
            name  = "DB_DRIVER"
            value = "maria"
          }
          env {
            name  = "DB_HOST"
            value = "myhost.azuredabases.com"
          }
          env {
            name  = "DB_PASSWORD"
            value = "mypwd"
          }
        }
	}
The table migrations is empty, as well as all other tables. Please find attached dump of the created database. 

[shlink.zip](https://github.com/shlinkio/shlink/files/5845415/shlink.zip)

**Comment by acelaya** [comment] 2021-01-21 14:26
I think with that I can give it a try and see if I can reproduce it.

**Comment by acelaya** [comment] 2021-01-29 08:29
I have just spinned up latest Shlink version (2.5.2) linked to a fresh MariaDB 10.3.23 database and it has worked with no issues.

Can you confirm if you let Shlink generate the database structure for you? You should start with a completely empty database.

**Comment by nmm-cargoclix** [comment] 2021-01-29 09:11
Yes, the database did not exist.

**Comment by acelaya** [comment] 2021-02-20 10:35
Hey @nmm-cargoclix, could you try with latest v2.6.0? I increased the timeout for the migrate command, and it's now based in PHP 8.

It's not that that should actually make a difference, but I'm being unable to reproduce this whatever way I try, so it's more a blind try than anything else.

**Comment by acelaya** [comment] 2021-02-20 11:36
Also, if you can try passing the `SHELL_VERBOSITY=3` env var to the pod, it will increase the verbosity on that error and probably show the whole stack trace.

**Comment by nmm-cargoclix** [comment] 2021-02-21 22:45
Thank you for your effort. I tried to update the existing 2.2 instance. Verbosity set to 3 as well. Pod log is: 

`Creating fresh database if needed...
Updating database...

In Process.php line 267:

  The command "'/usr/local/bin/php' 'vendor/doctrine/migrations/bin/doctrine-  
  migrations.php' 'migrations:migrate' '--no-interaction'" failed.

  Exit Code: 1(General error)

  Working directory: /etc/shlink

  Output:
  ================


  Error Output:
  ================

  In MetadataStorageError.php line 13:


    The metadata storage is not up to date, please run the sync-metadata-stor
  ag
    e command to fix this issue.




  migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--
  allow-no-migration] [--all-or-nothing [ALL-OR-NOTHING]] [--configuration CO
  NFIGURATION] [--em EM] [--conn CONN] [--] [<version>]


db:migrate`

**Comment by acelaya** [comment] 2021-05-30 11:24
I'm going to close this issue for now, as nobody else seems to be facing it, and I haven't been able to reproduce in any way I have tried.

There's definitely some combination making it fail, but without a clue, it's hard to find it, and it seems like a very edge case.

**Closed by acelaya** 2021-05-30 11:24 UTC
Labels: bug
