### ISSUE TITLE
Web server 500 code when requesting new domains REST endpoint

### ISSUE THREAD

**Issue by codaamok** [shlinkio/shlink#921] opened 2020-11-26 22:27 UTC
#### How Shlink is set-up

* Shlink Version: 2.4.2
* PHP Version: 7.4
* How do you serve Shlink: Self-hsoted nginx
* Database engine used: MariaDB 10.1.47-MariaDB-0ubuntu0.18.04.1

#### Summary

When querying new domains REST endpoint, I get a web server 500 error code. Querying the domains using the cli tool works no issue. I experience the same when I use https://api-spec.shlink.io/.

Here is the result of the CLI tool:

```
+--------------------+------------+
| Domain             | Is default |
+--------------------+------------+
| acook.io           | Yes        |
| cookadam.co.uk     | No         |
| www.cookadam.co.uk | No         |
+--------------------+------------+
```

#### Current behavior

Web code 500 is returned and the below is in the Shlink log when I call the endpoint

```
[2020-11-26T22:19:45.532528+00:00] [8b26b7bd-27fe-4aa5-8277-9e1fa05ddac4] Shlink.ERROR - BadMethodCallException: Undefined method 'findDomainsWithout'. The method name must start with either findBy, findOneBy or countBy! in /var/www/shlink/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php:235
Stack trace:
#0 /var/www/shlink/module/Core/src/Domain/DomainService.php(27): Doctrine\ORM\EntityRepository->__call()
#1 /var/www/shlink/module/Rest/src/Action/Domain/ListDomainsAction.php(32): Shlinkio\Shlink\Core\Domain\DomainService->listDomainsWithout()
#2 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Middleware/RequestHandlerMiddleware.php(54): Shlinkio\Shlink\Rest\Action\Domain\ListDomainsAction->handle()
#3 /var/www/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(47): Laminas\Stratigility\Middleware\RequestHandlerMiddleware->process()
#4 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(61): Mezzio\Middleware\LazyLoadingMiddleware->process()
#5 /var/www/shlink/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\Stratigility\Next->handle()
#6 /var/www/shlink/vendor/mezzio/mezzio-router/src/Route.php(91): Laminas\Stratigility\MiddlewarePipe->process()
#7 /var/www/shlink/vendor/mezzio/mezzio-router/src/RouteResult.php(103): Mezzio\Router\Route->process()
#8 /var/www/shlink/vendor/mezzio/mezzio-router/src/Middleware/DispatchMiddleware.php(36): Mezzio\Router\RouteResult->process()
#9 /var/www/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(47): Mezzio\Router\Middleware\DispatchMiddleware->process()
#10 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(61): Mezzio\Middleware\LazyLoadingMiddleware->process()
#11 /var/www/shlink/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\Stratigility\Next->handle()
#12 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(61): Laminas\Stratigility\MiddlewarePipe->process()
#13 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Middleware/PathMiddlewareDecorator.php(130): Laminas\Stratigility\Next->handle()
#14 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(54): class@anonymous->handle()
#15 /var/www/shlink/module/Rest/src/Middleware/AuthenticationMiddleware.php(55): Laminas\Stratigility\Next->handle()
#16 /var/www/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(47): Shlinkio\Shlink\Rest\Middleware\AuthenticationMiddleware->process()
#17 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(61): Mezzio\Middleware\LazyLoadingMiddleware->process()
#18 /var/www/shlink/module/Rest/src/Middleware/BodyParserMiddleware.php(36): Laminas\Stratigility\Next->handle()
#19 /var/www/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(47): Shlinkio\Shlink\Rest\Middleware\BodyParserMiddleware->process()
#20 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(61): Mezzio\Middleware\LazyLoadingMiddleware->process()
#21 /var/www/shlink/vendor/mezzio/mezzio-router/src/Middleware/ImplicitOptionsMiddleware.php(69): Laminas\Stratigility\Next->handle()
#22 /var/www/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(47): Mezzio\Router\Middleware\ImplicitOptionsMiddleware->process()
#23 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(61): Mezzio\Middleware\LazyLoadingMiddleware->process()
#24 /var/www/shlink/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\Stratigility\Next->handle()
#25 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Middleware/PathMiddlewareDecorator.php(68): Laminas\Stratigility\MiddlewarePipe->process()
#26 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(61): Laminas\Stratigility\Middleware\PathMiddlewareDecorator->process()
#27 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(54): Laminas\Stratigility\Next->handle()
#28 /var/www/shlink/vendor/mezzio/mezzio-router/src/Middleware/ImplicitHeadMiddleware.php(82): Laminas\Stratigility\Next->handle()
#29 /var/www/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(47): Mezzio\Router\Middleware\ImplicitHeadMiddleware->process()
#30 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(61): Mezzio\Middleware\LazyLoadingMiddleware->process()
#31 /var/www/shlink/vendor/mezzio/mezzio-router/src/Middleware/RouteMiddleware.php(56): Laminas\Stratigility\Next->handle()
#32 /var/www/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(47): Mezzio\Router\Middleware\RouteMiddleware->process()
#33 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(61): Mezzio\Middleware\LazyLoadingMiddleware->process()
#34 /var/www/shlink/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\Stratigility\Next->handle()
#35 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(61): Laminas\Stratigility\MiddlewarePipe->process()
#36 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(54): Laminas\Stratigility\Next->handle()
#37 /var/www/shlink/vendor/shlinkio/shlink-common/src/Middleware/CloseDbConnectionMiddleware.php(27): Laminas\Stratigility\Next->handle()
#38 /var/www/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(47): Shlinkio\Shlink\Common\Middleware\CloseDbConnectionMiddleware->process()
#39 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(61): Mezzio\Middleware\LazyLoadingMiddleware->process()
#40 /var/www/shlink/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\Stratigility\Next->handle()
#41 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(61): Laminas\Stratigility\MiddlewarePipe->process()
#42 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Middleware/PathMiddlewareDecorator.php(130): Laminas\Stratigility\Next->handle()
#43 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(54): class@anonymous->handle()
#44 /var/www/shlink/vendor/mezzio/mezzio-problem-details/src/ProblemDetailsMiddleware.php(60): Laminas\Stratigility\Next->handle()
#45 /var/www/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(47): Mezzio\ProblemDetails\ProblemDetailsMiddleware->process()
#46 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(61): Mezzio\Middleware\LazyLoadingMiddleware->process()
#47 /var/www/shlink/vendor/php-middleware/request-id/src/RequestIdMiddleware.php(32): Laminas\Stratigility\Next->handle()
#48 /var/www/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(47): PhpMiddleware\RequestId\RequestIdMiddleware->process()
#49 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(61): Mezzio\Middleware\LazyLoadingMiddleware->process()
#50 /var/www/shlink/module/Rest/src/Middleware/CrossDomainMiddleware.php(22): Laminas\Stratigility\Next->handle()
#51 /var/www/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(47): Shlinkio\Shlink\Rest\Middleware\CrossDomainMiddleware->process()
#52 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(61): Mezzio\Middleware\LazyLoadingMiddleware->process()
#53 /var/www/shlink/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\Stratigility\Next->handle()
#54 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Middleware/PathMiddlewareDecorator.php(68): Laminas\Stratigility\MiddlewarePipe->process()
#55 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(61): Laminas\Stratigility\Middleware\PathMiddlewareDecorator->process()
#56 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(54): Laminas\Stratigility\Next->handle()
#57 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Middleware/ErrorHandler.php(144): Laminas\Stratigility\Next->handle()
#58 /var/www/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(47): Laminas\Stratigility\Middleware\ErrorHandler->process()
#59 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(61): Mezzio\Middleware\LazyLoadingMiddleware->process()
#60 /var/www/shlink/vendor/mezzio/mezzio-helpers/src/ContentLengthMiddleware.php(32): Laminas\Stratigility\Next->handle()
#61 /var/www/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(47): Mezzio\Helper\ContentLengthMiddleware->process()
#62 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(61): Mezzio\Middleware\LazyLoadingMiddleware->process()
#63 /var/www/shlink/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\Stratigility\Next->handle()
#64 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(61): Laminas\Stratigility\MiddlewarePipe->process()
#65 /var/www/shlink/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\Stratigility\Next->handle()
#66 /var/www/shlink/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(73): Laminas\Stratigility\MiddlewarePipe->process()
#67 /var/www/shlink/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(96): Laminas\Stratigility\MiddlewarePipe->handle()
#68 /var/www/shlink/vendor/mezzio/mezzio/src/Application.php(82): Laminas\HttpHandlerRunner\RequestHandlerRunner->run()
#69 /var/www/shlink/config/run.php(14): Mezzio\Application->run()
#70 /var/www/shlink/public/index.php(6): {closure}()
#71 {main}
```

#### Expected behavior

To see see of domains used by shortcodes, i.e. web code 200

#### How to reproduce

Upgrade from 2.3.0 to 2.4.2 and call the domains endpoint. Not sure if the upgrade path has anything to do with it.

I'm happy to provide SSH access if interested, just email me.

**Comment by acelaya** [comment] 2020-11-27 01:47
What I think it's happening here is that some database config has been cached.

A recent version introduced a custom repository for the Domain entity, which includes the method findDomainsWithout.

The error indicates it is resolving a regular repository which does not have this method.

Since the error is not reproducible through the CLI, I think it has to be related with the APCu cache.

Can you try restarting the php-fpm and nginx services? That should clear that cache and fix the issue.

**Comment by codaamok** [comment] 2020-11-27 09:37
Restarting php-fpm service alone fixed it! Thank you!

**Comment by acelaya** [comment] 2020-11-27 09:50
Cool, glad to hear. I'll make sure to document this properly, or even improve the integration with the database cache so the the update script can reset it properly.

**Closed by acelaya** 2020-11-27 09:50 UTC
Labels: bug
