### ISSUE TITLE
QRCode endpoint broke on 3.0.0

### ISSUE THREAD

**Issue by wfjsw** [shlinkio/shlink#1361] opened 2022-01-30 13:00 UTC
#### How Shlink is set-up

* Shlink Version: 3.0.0 (Upgraded from 2.10.3)
* PHP Version: 8.1.1
* How do you serve Shlink: Self-hosted nginx
* Database engine used: PostgreSQL

#### Summary

Fetching QR Code of any shortlinks reports `An unexpected error occurred`

#### Stack Trace

```
[2022-01-30T12:54:46.180745+00:00] [46b55307-2ec5-4d4e-9bd3-707e74f514f7] Shlink.ERROR - RuntimeException: Index invalid or out of range in /vendor/bacon/bacon-qr-code/src/Encoder/MaskUtil.php:106
Stack trace:
#0 /vendor/bacon/bacon-qr-code/src/Encoder/Encoder.php(181): BaconQrCode\Encoder\MaskUtil::applyMaskPenaltyRule3()
#1 /vendor/bacon/bacon-qr-code/src/Encoder/Encoder.php(228): BaconQrCode\Encoder\Encoder::calculateMaskPenalty()
#2 /vendor/bacon/bacon-qr-code/src/Encoder/Encoder.php(119): BaconQrCode\Encoder\Encoder::chooseMaskPattern()
#3 /vendor/endroid/qr-code/src/Bacon/MatrixFactory.php(18): BaconQrCode\Encoder\Encoder::encode()
#4 /vendor/endroid/qr-code/src/Writer/SvgWriter.php(33): Endroid\QrCode\Bacon\MatrixFactory->create()
#5 /vendor/endroid/qr-code/src/Builder/Builder.php(231): Endroid\QrCode\Writer\SvgWriter->write()
#6 /module/Core/src/Action/QrCodeAction.php(51): Endroid\QrCode\Builder\Builder->build()
#7 /vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(37): Shlinkio\Shlink\Core\Action\QrCodeAction->process()
#8 /vendor/laminas/laminas-stratigility/src/Next.php(51): Mezzio\Middleware\LazyLoadingMiddleware->process()
#9 /vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(76): Laminas\Stratigility\Next->handle()
#10 /vendor/mezzio/mezzio-router/src/Route.php(85): Laminas\Stratigility\MiddlewarePipe->process()
#11 /vendor/mezzio/mezzio-router/src/RouteResult.php(97): Mezzio\Router\Route->process()
#12 /vendor/mezzio/mezzio-router/src/Middleware/DispatchMiddleware.php(30): Mezzio\Router\RouteResult->process()
#13 /vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(37): Mezzio\Router\Middleware\DispatchMiddleware->process()
#14 /vendor/laminas/laminas-stratigility/src/Next.php(51): Mezzio\Middleware\LazyLoadingMiddleware->process()
#15 /vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(76): Laminas\Stratigility\Next->handle()
#16 /vendor/laminas/laminas-stratigility/src/Next.php(51): Laminas\Stratigility\MiddlewarePipe->process()
#17 /vendor/laminas/laminas-stratigility/src/Middleware/PathMiddlewareDecorator.php(43): Laminas\Stratigility\Next->handle()
#18 /vendor/laminas/laminas-stratigility/src/Next.php(51): Laminas\Stratigility\Middleware\PathMiddlewareDecorator->process()
#19 /vendor/laminas/laminas-stratigility/src/Next.php(44): Laminas\Stratigility\Next->handle()
#20 /vendor/mezzio/mezzio-router/src/Middleware/ImplicitHeadMiddleware.php(76): Laminas\Stratigility\Next->handle()
#21 /vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(37): Mezzio\Router\Middleware\ImplicitHeadMiddleware->process()
#22 /vendor/laminas/laminas-stratigility/src/Next.php(51): Mezzio\Middleware\LazyLoadingMiddleware->process()
#23 /vendor/mezzio/mezzio-router/src/Middleware/RouteMiddleware.php(50): Laminas\Stratigility\Next->handle()
#24 /vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(37): Mezzio\Router\Middleware\RouteMiddleware->process()
#25 /vendor/laminas/laminas-stratigility/src/Next.php(51): Mezzio\Middleware\LazyLoadingMiddleware->process()
#26 /vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(76): Laminas\Stratigility\Next->handle()
#27 /vendor/laminas/laminas-stratigility/src/Next.php(51): Laminas\Stratigility\MiddlewarePipe->process()
#28 /vendor/laminas/laminas-stratigility/src/Next.php(44): Laminas\Stratigility\Next->handle()
#29 /vendor/shlinkio/shlink-common/src/Middleware/CloseDbConnectionMiddleware.php(24): Laminas\Stratigility\Next->handle()
#30 /vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(37): Shlinkio\Shlink\Common\Middleware\CloseDbConnectionMiddleware->process()
#31 /vendor/laminas/laminas-stratigility/src/Next.php(51): Mezzio\Middleware\LazyLoadingMiddleware->process()
#32 /vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(76): Laminas\Stratigility\Next->handle()
#33 /vendor/laminas/laminas-stratigility/src/Next.php(51): Laminas\Stratigility\MiddlewarePipe->process()
#34 /vendor/laminas/laminas-stratigility/src/Middleware/PathMiddlewareDecorator.php(43): Laminas\Stratigility\Next->handle()
#35 /vendor/laminas/laminas-stratigility/src/Next.php(51): Laminas\Stratigility\Middleware\PathMiddlewareDecorator->process()
#36 /vendor/laminas/laminas-stratigility/src/Next.php(44): Laminas\Stratigility\Next->handle()
#37 /module/Rest/src/Middleware/CrossDomainMiddleware.php(25): Laminas\Stratigility\Next->handle()
#38 /vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(37): Shlinkio\Shlink\Rest\Middleware\CrossDomainMiddleware->process()
#39 /vendor/laminas/laminas-stratigility/src/Next.php(51): Mezzio\Middleware\LazyLoadingMiddleware->process()
#40 /vendor/laminas/laminas-stratigility/src/Middleware/ErrorHandler.php(131): Laminas\Stratigility\Next->handle()
#41 /vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(37): Laminas\Stratigility\Middleware\ErrorHandler->process()
#42 /vendor/laminas/laminas-stratigility/src/Next.php(51): Mezzio\Middleware\LazyLoadingMiddleware->process()
#43 /vendor/php-middleware/request-id/src/RequestIdMiddleware.php(32): Laminas\Stratigility\Next->handle()
#44 /vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(37): PhpMiddleware\RequestId\RequestIdMiddleware->process()
#45 /vendor/laminas/laminas-stratigility/src/Next.php(51): Mezzio\Middleware\LazyLoadingMiddleware->process()
#46 /vendor/shlinkio/shlink-common/src/Middleware/ContentLengthMiddleware.php(24): Laminas\Stratigility\Next->handle()
#47 /vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(37): Shlinkio\Shlink\Common\Middleware\ContentLengthMiddleware->process()
#48 /vendor/laminas/laminas-stratigility/src/Next.php(51): Mezzio\Middleware\LazyLoadingMiddleware->process()
#49 /vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(76): Laminas\Stratigility\Next->handle()
#50 /vendor/laminas/laminas-stratigility/src/Next.php(51): Laminas\Stratigility\MiddlewarePipe->process()
#51 /vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(76): Laminas\Stratigility\Next->handle()
#52 /vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(65): Laminas\Stratigility\MiddlewarePipe->process()
#53 /vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(82): Laminas\Stratigility\MiddlewarePipe->handle()
#54 /vendor/mezzio/mezzio/src/Application.php(68): Laminas\HttpHandlerRunner\RequestHandlerRunner->run()
#55 /config/run.php(13): Mezzio\Application->run()
#56 /public/index.php(5): {closure}()
#57 {main}
```

#### How to reproduce

Access `http://example.com/short-code/qr-code`

**Comment by wfjsw** [comment] 2022-01-30 13:02
Seems related: https://github.com/Bacon/BaconQrCode/issues/92

**Comment by acelaya** [comment] 2022-01-30 16:48
I have subscribed to the issue. I'll include a version of the fixed dependency on Shlink 3.0.1

**Comment by wfjsw** [comment] 2022-01-30 17:08
I suspect that library is properly maintained now at all.

**Comment by acelaya** [comment] 2022-01-30 17:57
Yep, definitely looks abandoned.

I've opened the discussion in the library Shlink depends on. The one failing is a dependency of theirs.

https://github.com/endroid/qr-code/issues/365

**Comment by acelaya** [comment] 2022-01-30 18:02
@wfjsw can you share the details to reproduce it? I have tried with a couple of QR codes and they work for me, so there's probably a specific combination which can fail.

I would need to know the long URL, format, size, margin and error correction you used.

**Comment by wfjsw** [comment] 2022-01-30 18:12
well wtf it's magically fixed on my side ???

**Comment by acelaya** [comment] 2022-01-30 18:21
That's weird 😅

**Comment by acelaya** [comment] 2022-02-01 20:35
Closing for now, as nobody seems to be able to reproduce it, and the issue in the dependency has been closed as well.

**Closed** 2022-02-01 20:35 UTC
Labels: bug
