### ISSUE TITLE
Unknown database type "_text" requested, Doctrine\DBAL\Platforms\PostgreSQL

### ISSUE THREAD

**Issue by MaxwellDAssistek** [shlinkio/shlink#2254] opened 2024-11-10 05:36 UTC
### Shlink version

4.2.5

### PHP version

built-in

### How do you serve Shlink

Docker image

### Database engine

PostgreSQL

### Database version

PostgreSQL 16.3

### Current behavior

When the container is first started, I get the following error:

```
Initializing database if needed... [Running "/usr/local/bin/php bin/cli db:create"]   RUN  '/usr/local/bin/php' 'bin/cli' 'db:create'
  OUT  
  OUT   [OK] Database already exists. Run "db:migrate" command to make sure it is up to
  OUT        date.                                                                     
  OUT  
  OUT  
  RES  Command ran successfully
 Success!
Updating database... [Running "/usr/local/bin/php bin/cli db:migrate"]   RUN  '/usr/local/bin/php' 'bin/cli' 'db:migrate'
  OUT  Migrating database...
  OUT  
  ERR    RUN  '/usr/local/bin/php' 'vendor/doctrine/migrations/bin/doctrine-migrations.php' 'migrations:migrate' '--no-interaction'
  ERR    ERR  
  ERR    ERR  In AbstractPlatform.php line 349:
  ERR    ERR                                                                                 
  ERR    ERR    [Doctrine\DBAL\Exception\InvalidArgumentException]                           
  ERR    ERR    Unknown database type "_text" requested, Doctrine\DBAL\Platforms\PostgreSQL  
  ERR    ERR    120Platform may not support it.                                              
  ERR    ERR                                                                                 
  ERR    ERR  
  ERR    ERR  Exception trace:
  ERR    ERR    at /etc/shlink/vendor/doctrine/dbal/src/Platforms/AbstractPlatform.php:349
  ERR    ERR   Doctrine\DBAL\Platforms\AbstractPlatform->getDoctrineTypeMapping() at /etc/shlink/vendor/doctrine/dbal/src/Schema/PostgreSQLSchemaManager.php:273
  ERR    ERR   Doctrine\DBAL\Schema\PostgreSQLSchemaManager->_getPortableTableColumnDefinition() at /etc/shlink/vendor/doctrine/dbal/src/Schema/AbstractSchemaManager.php:670
  ERR    ERR   Doctrine\DBAL\Schema\AbstractSchemaManager->_getPortableTableColumnList() at /etc/shlink/vendor/doctrine/dbal/src/Schema/AbstractSchemaManager.php:210
  ERR    ERR   Doctrine\DBAL\Schema\AbstractSchemaManager->listTables() at /etc/shlink/vendor/doctrine/dbal/src/Schema/AbstractSchemaManager.php:802
  ERR    ERR   Doctrine\DBAL\Schema\AbstractSchemaManager->introspectSchema() at /etc/shlink/vendor/doctrine/migrations/src/Provider/DBALSchemaDiffProvider.php:32
  ERR    ERR   Doctrine\Migrations\Provider\DBALSchemaDiffProvider->createFromSchema() at /etc/shlink/vendor/doctrine/migrations/src/Provider/LazySchemaDiffProvider.php:26
  ERR    ERR   Doctrine\Migrations\Provider\LazySchemaDiffProvider::Doctrine\Migrations\Provider\{closure}() at /etc/shlink/vendor/symfony/var-exporter/LazyProxyTrait.php:107
  ERR    ERR   Doctrine\Migrations\Provider\LazySchema->__get() at /etc/shlink/vendor/symfony/var-exporter/LazyProxyTrait.php:136
  ERR    ERR   Doctrine\Migrations\Provider\LazySchema->__get() at /etc/shlink/vendor/doctrine/dbal/src/Schema/AbstractAsset.php:118
  ERR    ERR   Doctrine\DBAL\Schema\AbstractAsset->getName() at /etc/shlink/vendor/doctrine/dbal/src/Schema/Schema.php:172
  ERR    ERR   Doctrine\DBAL\Schema\Schema->getFullQualifiedAssetName() at /etc/shlink/vendor/doctrine/dbal/src/Schema/Schema.php:224
  ERR    ERR   Doctrine\DBAL\Schema\Schema->hasTable() at /etc/shlink/module/Core/migrations/Version20230103105343.php:18
  ERR    ERR   ShlinkMigrations\Version20230103105343->up() at /etc/shlink/vendor/doctrine/migrations/src/Version/DbalExecutor.php:138
  ERR    ERR   Doctrine\Migrations\Version\DbalExecutor->executeMigration() at /etc/shlink/vendor/doctrine/migrations/src/Version/DbalExecutor.php:72
  ERR    ERR   Doctrine\Migrations\Version\DbalExecutor->execute() at /etc/shlink/vendor/doctrine/migrations/src/DbalMigrator.php:87
  ERR    ERR   Doctrine\Migrations\DbalMigrator->executePlan() at /etc/shlink/vendor/doctrine/migrations/src/DbalMigrator.php:54
  ERR    ERR   Doctrine\Migrations\DbalMigrator->executeMigrations() at /etc/shlink/vendor/doctrine/migrations/src/DbalMigrator.php:134
  ERR    ERR   Doctrine\Migrations\DbalMigrator->migrate() at /etc/shlink/vendor/doctrine/migrations/src/Tools/Console/Command/MigrateCommand.php:225
  ERR    ERR   Doctrine\Migrations\Tools\Console\Command\MigrateCommand->execute() at /etc/shlink/vendor/symfony/console/Command/Command.php:279
  ERR    ERR   Symfony\Component\Console\Command\Command->run() at /etc/shlink/vendor/symfony/console/Application.php:1029
  ERR    ERR   Symfony\Component\Console\Application->doRunCommand() at /etc/shlink/vendor/symfony/console/Application.php:316
  ERR    ERR   Symfony\Component\Console\Application->doRun() at /etc/shlink/vendor/symfony/console/Application.php:167
  ERR    ERR   Symfony\Component\Console\Application->run() at /etc/shlink/vendor/doctrine/migrations/src/Tools/Console/ConsoleRunner.php:95
  ERR    ERR   Doctrine\Migrations\Tools\Console\ConsoleRunner::run() at /etc/shlink/vendor/doctrine/migrations/bin/doctrine-migrations.php:45
  ERR    ERR   Doctrine\Migrations\{closure}() at /etc/shlink/vendor/doctrine/migrations/bin/doctrine-migrations.php:46
  ERR    ERR  
  ERR    ERR  migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--allow-no-migration] [--all-or-nothing [ALL-OR-NOTHING]] [--no-all-or-nothing] [--configuration CONFIGURATION] [--em EM] [--conn CONN] [--] [<version>]
  ERR    ERR  
  ERR    ERR  
  ERR  In Process.php line 269:
  ERR                                                                                 
  ERR    [Symfony\Component\Process\Exception\ProcessFailedException]                 
  ERR    The command "'/usr/local/bin/php' 'vendor/doctrine/migrations/bin/doctrine-  
  ERR    migrations.php' 'migrations:migrate' '--no-interaction'" failed.             
  ERR                                                                                 
  ERR    Exit Code: 1(General error)                                                  
  ERR                                                                                 
  ERR    Working directory: /etc/shlink                                               
  ERR                                                                                 
  ERR    Output:                                                                      
  ERR    ================                                                             
  ERR                                                                                 
  ERR                                                                                 
  ERR    Error Output:                                                                
  ERR    ================                                                             
  ERR                                                                                 
  ERR    In AbstractPlatform.php line 349:                                            
  ERR                                                                                 
  ERR                                                                                 
  ERR      [Doctrine\DBAL\Exception\InvalidArgumentException]                         
  ERR                                                                                 
  ERR      Unknown database type "_text" requested, Doctrine\DBAL\Platforms\PostgreS  
  ERR    QL                                                                           
  ERR      120Platform may not support it.                                            
  ERR                                                                                 
  ERR                                                                                 
  ERR                                                                                 
  ERR                                                                                 
  ERR    Exception trace:                                                             
  ERR      at /etc/shlink/vendor/doctrine/dbal/src/Platforms/AbstractPlatform.php:34  
  ERR    9                                                                            
  ERR     Doctrine\DBAL\Platforms\AbstractPlatform->getDoctrineTypeMapping() at /etc  
  ERR    /shlink/vendor/doctrine/dbal/src/Schema/PostgreSQLSchemaManager.php:273      
  ERR     Doctrine\DBAL\Schema\PostgreSQLSchemaManager->_getPortableTableColumnDefin  
  ERR    ition() at /etc/shlink/vendor/doctrine/dbal/src/Schema/AbstractSchemaManage  
  ERR    r.php:670                                                                    
  ERR     Doctrine\DBAL\Schema\AbstractSchemaManager->_getPortableTableColumnList()   
  ERR    at /etc/shlink/vendor/doctrine/dbal/src/Schema/AbstractSchemaManager.php:21  
  ERR    0                                                                            
  ERR     Doctrine\DBAL\Schema\AbstractSchemaManager->listTables() at /etc/shlink/ve  
  ERR    ndor/doctrine/dbal/src/Schema/AbstractSchemaManager.php:802                  
  ERR     Doctrine\DBAL\Schema\AbstractSchemaManager->introspectSchema() at /etc/shl  
  ERR    ink/vendor/doctrine/migrations/src/Provider/DBALSchemaDiffProvider.php:32    
  ERR     Doctrine\Migrations\Provider\DBALSchemaDiffProvider->createFromSchema() at  
  ERR     /etc/shlink/vendor/doctrine/migrations/src/Provider/LazySchemaDiffProvider  
  ERR    .php:26                                                                      
  ERR     Doctrine\Migrations\Provider\LazySchemaDiffProvider::Doctrine\Migrations\P  
  ERR    rovider\{closure}() at /etc/shlink/vendor/symfony/var-exporter/LazyProxyTra  
  ERR    it.php:107                                                                   
  ERR     Doctrine\Migrations\Provider\LazySchema->__get() at /etc/shlink/vendor/sym  
  ERR    fony/var-exporter/LazyProxyTrait.php:136                                     
  ERR     Doctrine\Migrations\Provider\LazySchema->__get() at /etc/shlink/vendor/doc  
  ERR    trine/dbal/src/Schema/AbstractAsset.php:118                                  
  ERR     Doctrine\DBAL\Schema\AbstractAsset->getName() at /etc/shlink/vendor/doctri  
  ERR    ne/dbal/src/Schema/Schema.php:172                                            
  ERR     Doctrine\DBAL\Schema\Schema->getFullQualifiedAssetName() at /etc/shlink/ve  
  ERR    ndor/doctrine/dbal/src/Schema/Schema.php:224                                 
  ERR     Doctrine\DBAL\Schema\Schema->hasTable() at /etc/shlink/module/Core/migrati  
  ERR    ons/Version20230103105343.php:18                                             
  ERR     ShlinkMigrations\Version20230103105343->up() at /etc/shlink/vendor/doctrin  
  ERR    e/migrations/src/Version/DbalExecutor.php:138                                
  ERR     Doctrine\Migrations\Version\DbalExecutor->executeMigration() at /etc/shlin  
  ERR    k/vendor/doctrine/migrations/src/Version/DbalExecutor.php:72                 
  ERR     Doctrine\Migrations\Version\DbalExecutor->execute() at /etc/shlink/vendor/  
  ERR    doctrine/migrations/src/DbalMigrator.php:87                                  
  ERR     Doctrine\Migrations\DbalMigrator->executePlan() at /etc/shlink/vendor/doct  
  ERR    rine/migrations/src/DbalMigrator.php:54                                      
  ERR     Doctrine\Migrations\DbalMigrator->executeMigrations() at /etc/shlink/vendo  
  ERR    r/doctrine/migrations/src/DbalMigrator.php:134                               
  ERR     Doctrine\Migrations\DbalMigrator->migrate() at /etc/shlink/vendor/doctrine  
  ERR    /migrations/src/Tools/Console/Command/MigrateCommand.php:225                 
  ERR     Doctrine\Migrations\Tools\Console\Command\MigrateCommand->execute() at /et  
  ERR    c/shlink/vendor/symfony/console/Command/Command.php:279                      
  ERR     Symfony\Component\Console\Command\Command->run() at /etc/shlink/vendor/sym  
  ERR    fony/console/Application.php:1029                                            
  ERR     Symfony\Component\Console\Application->doRunCommand() at /etc/shlink/vendo  
  ERR    r/symfony/console/Application.php:316                                        
  ERR     Symfony\Component\Console\Application->doRun() at /etc/shlink/vendor/symfo  
  ERR    ny/console/Application.php:167                                               
  ERR     Symfony\Component\Console\Application->run() at /etc/shlink/vendor/doctrin  
  ERR    e/migrations/src/Tools/Console/ConsoleRunner.php:95                          
  ERR     Doctrine\Migrations\Tools\Console\ConsoleRunner::run() at /etc/shlink/vend  
  ERR    or/doctrine/migrations/bin/doctrine-migrations.php:45                        
  ERR     Doctrine\Migrations\{closure}() at /etc/shlink/vendor/doctrine/migrations/  
  ERR    bin/doctrine-migrations.php:46                                               
  ERR                                                                                 
  ERR    migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--  
  ERR    allow-no-migration] [--all-or-nothing [ALL-OR-NOTHING]] [--no-all-or-nothin  
  ERR    g] [--configuration CONFIGURATION] [--em EM] [--conn CONN] [--] [<version>]  
  ERR                                                                                 
  ERR  
  ERR  Exception trace:
  ERR    at /etc/shlink/vendor/symfony/process/Process.php:269
  ERR   Symfony\Component\Process\Process->mustRun() at /etc/shlink/module/CLI/src/Util/ProcessRunner.php:48
  ERR   Shlinkio\Shlink\CLI\Util\ProcessRunner->run() at /etc/shlink/module/CLI/src/Command/Db/AbstractDatabaseCommand.php:30
  ERR   Shlinkio\Shlink\CLI\Command\Db\AbstractDatabaseCommand->runPhpCommand() at /etc/shlink/module/CLI/src/Command/Db/MigrateDatabaseCommand.php:31
  ERR   Shlinkio\Shlink\CLI\Command\Db\MigrateDatabaseCommand->lockedExecute() at /etc/shlink/module/CLI/src/Command/Util/AbstractLockedCommand.php:35
  ERR   Shlinkio\Shlink\CLI\Command\Util\AbstractLockedCommand->execute() at /etc/shlink/vendor/symfony/console/Command/Command.php:279
  ERR   Symfony\Component\Console\Command\Command->run() at /etc/shlink/vendor/symfony/console/Application.php:1029
  ERR   Symfony\Component\Console\Application->doRunCommand() at /etc/shlink/vendor/symfony/console/Application.php:316
  ERR   Symfony\Component\Console\Application->doRun() at /etc/shlink/vendor/symfony/console/Application.php:167
  ERR   Symfony\Component\Console\Application->run() at /etc/shlink/bin/cli:10
  ERR  
  ERR  db:migrate
  ERR  
  ERR  
  RES  1 Command did not run successfully
Generating proxies... [Running "/usr/local/bin/php bin/doctrine orm:generate-proxies"]   RUN  '/usr/local/bin/php' 'bin/doctrine' 'orm:generate-proxies'
  ERR   Processing entity "Shlinkio\Shlink\Core\ShortUrl\Entity\ShortUrl"
  ERR   Processing entity "Shlinkio\Shlink\Core\RedirectRule\Entity\RedirectCondition"
  ERR   Processing entity "Shlinkio\Shlink\Core\Tag\Entity\Tag"
  ERR   Processing entity "Shlinkio\Shlink\Core\Visit\Entity\ShortUrlVisitsCount"
  ERR   Processing entity "Shlinkio\Shlink\Core\RedirectRule\Entity\ShortUrlRedirectRule"
  ERR   Processing entity "Shlinkio\Shlink\Core\Visit\Entity\OrphanVisitsCount"
  ERR   Processing entity "Shlinkio\Shlink\Core\Visit\Entity\Visit"
  ERR   Processing entity "Shlinkio\Shlink\Core\Domain\Entity\Domain"
  ERR   Processing entity "Shlinkio\Shlink\Core\Visit\Entity\VisitLocation"
  ERR   Processing entity "Shlinkio\Shlink\Rest\Entity\ApiKeyRole"
  ERR   Processing entity "Shlinkio\Shlink\Rest\Entity\ApiKey"
  ERR  
  ERR   Proxy classes generated to "/etc/shlink/data/proxies"
  ERR  
  RES  Command ran successfully
 Success!
Clearing entities cache... [Running "/usr/local/bin/php bin/doctrine orm:clear-cache:metadata"]   RUN  '/usr/local/bin/php' 'bin/doctrine' 'orm:clear-cache:metadata'
  ERR  
  ERR   // Clearing all Metadata cache entries                                         
  ERR  
  ERR   [OK] Successfully deleted cache entries.                                       
  ERR  
  ERR  
  RES  Command ran successfully
 Success!
Downloading GeoLite2 db file... [Running "/usr/local/bin/php bin/cli visit:download-db"]   RUN  '/usr/local/bin/php' 'bin/cli' 'visit:download-db'
  OUT   Downloading GeoLite2 db file...
  OUT      0 [>---------------------------] < 1 sec 8.0 MiB
  OUT    2736128/26785843 [==>-------------------------]  10%  1 sec/10 secs 8.0 MiB
  OUT    5500928/26785843 [=====>----------------------]  20%  1 sec/5 secs 8.0 MiB
  OUT    8122368/26785843 [========>-------------------]  30%  1 sec/3 secs 8.0 MiB
  OUT   13443072/26785843 [==============>-------------]  50%  1 sec/2 secs 8.0 MiB
  OUT   18874368/26785843 [===================>--------]  70%  1 sec/1 sec  8.0 MiB
  OUT   21430272/26785843 [======================>-----]  80%  1 sec/1 sec  8.0 MiB
  OUT   24113152/26785843 [=========================>--]  90%  1 sec/1 sec  8.0 MiB
  OUT   26785843/26785843 [============================] 100%  1 sec/1 sec  8.0 MiB
  OUT  
  OUT   [OK] GeoLite2 db file properly downloaded.                                     
  OUT  
  OUT  
  RES  Command ran successfully
 Success!
```

### Expected behavior

Container should complete migration and start.

### Minimum steps to reproduce

Set up the following environment variables:

```
env:
    GEOLITE_LICENSE_KEY: "<My Key>"
    DEFAULT_DOMAIN: "<my url>"
    IS_HTTPS_ENABLED: "true"
    DB_DRIVER: "postgres"
    DB_USER: "shlink"
    DB_PASSWORD: "shlink"
    DB_HOST: "shlink-postgresql"
    SHELL_VERBOSITY: "3"
```

**Comment by acelaya** [comment] 2024-11-10 08:21
This works for me:

```yml
services:
  shlink:
    image: shlinkio/shlink:4.2.5
    ports:
      - "8080:8080"
    links:
      - shlink-postgresql
    depends_on:
      - shlink-postgresql
    environment:
      DEFAULT_DOMAIN: "localhost:8080"
      IS_HTTPS_ENABLED: "false"
      DB_DRIVER: "postgres"
      DB_USER: "postgres"
      DB_PASSWORD: "shlink"
      DB_HOST: "shlink-postgresql"
      SHELL_VERBOSITY: "3"
  
  shlink-postgresql:
    image: postgres:16.3
    environment:
      POSTGRES_PASSWORD: shlink
      POSTGRES_DB: shlink
```

Can you provide a docker-compose file where the issue can be reproduce consistently?

**Comment by acelaya** [comment] 2024-11-11 07:19
Closing as not reproducible. I'm happy to re-open if more specific details are provided.

**Closed by acelaya** 2024-11-11 07:19 UTC
Labels: bug
