### ISSUE TITLE
Run in a subfolder with nginx

### ISSUE THREAD

**Issue by poblabs** [shlinkio/shlink#481] opened 2019-09-12 01:41 UTC
I'd like to run shlink in a subfolder with nginx. I can't seem to come up with the right `location` combination. Has anyone else tried this?

For example, http://example.com/go/

**Comment by acelaya** [comment] 2019-09-12 05:25
It's not the most usual use case, so shlink won't support it out of the box.

However, it should be possible to remove the path prefix (/go in your example) using some nginx rule. I will take a look later, because I think I've done something similar in the past.

Also, I will create an issue to add support for this. It should be easy to allow providing a base path so that routes properly match when shlink is served from a subfolder.

**Comment by poblabs** [comment] 2019-09-13 12:06
> The public folder is the project's document root.

I understand this. But even when changing the project root to `/public` I was getting a stylized 404 - which looked like it came from shlink. Maybe this is natural?

The 403 is from nginx when there's no index found, so that explains the previous 403's

**Comment by acelaya** [comment] 2019-09-13 12:11
The 404 is coming from shlink. When you are in that case is when you could try to play with nginx rules to see if something works.

Out of the box it returns 404 always because nginx is passing the URL with the subfolder prefix, and shlink is not capable of matching any route.

That's what will change when #482 is implemented.

For now, if no nginx rule seems to work, I would recommend the use of a subdomain instead

**Comment by poblabs** [comment] 2019-09-13 12:14
Thanks! I'll keep playing around with it. I also have the subdomain setup, too.

**Comment by acelaya** [comment] 2019-09-13 12:17
Perfect!

Sorry I couldn't help you find the solution. I was playing a bit with nginx yesterday but I couldn't find a working set of rules.

The support for subpaths will be part of v1.19, which will take a couple of weeks to be ready. I'll let you know when it's there.

**Comment by poblabs** [comment] 2019-09-13 12:18
No worries. I'll keep playing around with it too 😃

**Comment by poblabs** [comment] 2019-09-13 18:17
For my future self (or anyone else), I was able to use nginx to redirect my old `/go/` subfolder to my `go.example.com` website with the following location rule. It's working pretty good. 

Working well enough that I've moved my other domain's `/go/` folder to it too. So 2 domain's subfolders to the 1 subdomain. 

So far it doesn't look like I'll lose my already-published short urls. 

```
    location ^~ /go/ {
        rewrite ^/go/(.*) http://go.example.com/$1;
    }
```

**Closed** 2019-09-13 18:54 UTC
Labels: meta-issue, question

**Comment by acelaya** [comment] 2019-09-13 18:56
Hey @poblabs 

The issue is closed because the feature is already implemented and merged.

Next release will allow you to define the base path from which shlink is being served and work out of the box without having to add any nginx rule.

**Comment by poblabs** [comment] 2019-09-13 23:33
Great news, thanks!

**Comment by Grief** [comment] 2022-02-07 10:55
@acelaya could you please share the config for nginx to make shlink be working in a sub-path of a domain? You said it should work 'out of the box' but I am not sure how. The config here does not work: https://shlink.io/documentation/classic-web-server/#nginx

**Comment by acelaya** [comment] 2022-02-07 11:27
I meant out of the box from Poblabs configuration. The one in the docs assumed you are serving Shlink from the root of the domain.

**Comment by Grief** [comment] 2022-02-07 11:34
@acelaya could you please share the whole config which is supposed to work with the sub path?

**Comment by acelaya** [comment] 2022-02-07 11:44
Can you open a new discussion to avoid notifying unrelated people and hiding information in old tickets?

**Comment by Grief** [comment] 2022-02-07 12:00
Sure, https://github.com/shlinkio/shlink/issues/1371
