### ISSUE TITLE
Silent Database migration error

### ISSUE THREAD

**Issue by SirFlip** [shlinkio/shlink#525] opened 2019-11-02 11:22 UTC
#### How Shlink is set-up

* Shlink Version: 1.18.1 -> 1.19.0
* PHP Version: 7.3.11
* How do you serve Shlink: Self-hosted Apache
* Database engine used: MariaDB (was 10.1 -> now 10.4)

#### Summary
On thw update it said the database upgrad was successfull.
But when I tried I got an 500 Internal Server Error.
I then found out that the the migration didn't work so I tried it manualy. (See screenshot below)
It produced an error. Which I could then fixed by upgradeing to a MariaDB 10.4
After this the migration worked.
But I still get the 500 error when opening a short-url.
Log file: https://gist.github.com/SirFlip/b3656ac91a4ce23890748335f3281f47

#### Current behavior

500 Internal Server Error

![grafik](https://user-images.githubusercontent.com/6735323/68070105-114b0280-fd6a-11e9-9c08-9098383a9e4b.png)
![grafik](https://user-images.githubusercontent.com/6735323/68070099-03957d00-fd6a-11e9-9d2c-637365628eff.png)

**Comment by SirFlip** [comment] 2019-11-02 20:45
Note: just upgraded to version 1.20.0 error still exists

**Comment by acelaya** [comment] 2019-11-02 21:00
I see three different errors here.

The first one is that the migrations command failed silently. I will investigate that in order to prevent it for futurte releases.

The second issue is that, once you have managed to see the error, it was failing to create an index. I have tested this with MariaDB 10.2, but not with previous versions.

You mention that you managed to solve this one. Did it solve when updating the database engine?

The third error is the one related with the log. That error is probably caused by the entity proxies not being properly regenerated during the project update.

Try deleting all files inside `data/proxies`, and then run `php ./vendor/bin/doctrine orm:generate-proxies` from the project root, which should regenerate those proxies.

Let me know if, after doing that, the problem is solved.

**Comment by SirFlip** [comment] 2019-11-02 21:13
> You mention that you managed to solve this one. Did it solve when updating the database engine?

Yes this was solve with the MariaDB upgrade

ok I tried deleting the proxies and recreate them. But the error still exists. As far as I see the error stays the same. (See bottom file in gist)

**Comment by SirFlip** [comment] 2019-11-02 21:48
Just to let you know I did some more tests on the same server:
I install a brand new instance: everything works fine
And I tried to upgrade an other shlink instance: the same error
 
Then just out of curiosity I ran the `bin/update` again with the previous path option as `.` and now it works again.

So if you don't need the issue for further investigation you can close it. For me it appears to be solved.
Thanks for your help!!!

**Comment by acelaya** [comment] 2019-11-02 21:51
I'm glad to hear it's working :)

I will do some further testing to try to reproduce it, but I'll close this issue for now.

Let me know if you need anything else. Thanks!

**Closed by acelaya** 2019-11-02 21:51 UTC
Labels: bug
