### ISSUE TITLE
[Feature Request] Proxy Shlink

### ISSUE THREAD

**Issue by MartinHotmann** [shlinkio/shlink#1170] opened 2021-09-08 11:31 UTC
#### Summary

ATM people can shlink links and make nice cool short.links out of it and it is pretty handy. But sometimes I want to have a shortlink which does not expose the real long link for personal, privacy and control reasons.

ATM:
https://shlink.to/abc ==> https://www.domain.tld/longUglyLinkWithManyChars

and if someone klicks on https://shlink.to/abc they get redirected/forwarded to the long ugly link which also gets exposed to them.

For more control and privacy I would like to suggest implementing a "Proxy Shlink" mode which can be activated if allowed on the server. The Server then (on request to the shlink) does not forward but in the background fetches the long URL and serves it under the short URL to the client.

All functionalioty, tracking the will still be available, but you will gain more control, also over "how often a Link can be called because with the foirwarding the real URL will get exposed to the client and he then can call the real URL as often as he wanted without getting tracked.

I think this would be a great addition to already existing shlink functionality and could be done with a manual fetch or a good reverse proxy like "nginx" etc.

Best regards

Only disadvantage: Traffic will be routed through your server.
Also this option shall be activated through config, otherwise setting up a proxyShlink shall not work. I can imagine public link shortener want to deactivate it for not having to handle much traffic.

**Comment by acelaya** [comment] 2021-09-11 06:13
Interesting.

Would you expect this option to be a global toggle that makes either all or none of the urls to behave like this? Or would you instead expect it it to be enabled on a per-url basis?

**Comment by NReilingh** [comment] 2021-09-11 18:36
As someone who knows a bit about what this would require technically, I would say it's completely out of scope for Shlink as a project. Attempts to do this have no end to difficulties with CORS, relative paths, content rewriting, SSL issues, and load balancing/rate limiting. It's extremely dependent on the upstream service being proxied, and anything on the public internet not controlled by you and designed for this purpose will almost never work as intended.

**Comment by acelaya** [comment] 2021-09-11 18:43
Definitely good points (I'm mainly worried about the CORS one).

Also, the referenced page can potentially have many links still pointing to the original URL, which would defeat the purpose of hiding it.

Could still be done, by warning this to users and let them do it if desired, knowing the potential problems, but for the sake of focusing efforts on more useful features, and to avoid a stream of new issues opened because of confusing behaviors, I think the right thing to do is to not implement this.

The effort is too high for too little benefit.

**Closed by acelaya** 2021-09-11 18:43 UTC
Labels: feature

**Comment by MartinHotmann** [comment] 2021-09-11 18:59
> Attempts to do this have no end to difficulties with CORS

Not if you configure your CORS policy at the resource properly.

> relative paths, content rewriting

I was not talking about "proxying websites" but files. With files, there are NO problems with path or content rewriting

> SSL issues, and load balancing/rate limiting.

Never encountered SSL issues when I proxy something. Also, I do not understand why you talk about load-balancing or rate limiting. Yes, if you hit a rate limit you hit a rate limit… but that's not just the case if you proxy.


I do know what a proxy is, and I do have knowledge and experience with proxies and never encountered these from you mentioned issues. If you want to proxy websites or content that you do not own, then yes, this could fail to hide things.

> Would you expect this option to be a global toggle that makes either all or none of the urls to behave like this? Or would you instead expect it to be enabled on a per-url basis?

The config should be global, or no config at all, but users should be able to decide if they want to proxy or just shorten for each shlink they create.

Anyway if the effort is too high I can understand and accept this.

**Comment by NReilingh** [comment] 2021-09-11 20:38
Sorry if I came off a little strong @MartinHotmann. You didn't mention limiting scope to individual files or only proxying your own resources, and given that Shlink is typically used for websites, that's what one would expect a proxy feature to support.

Regarding rate limiting, the scenario is if you have thousands of people all being redirected to one resource, they all appear as different agents (different IPs) to the server, whereas if you are proxying all of those requests, then the upstream server will see an outsized amount of traffic from your proxy's IP and may treat it as hostile/rate limit it. Again, not an issue if you're hosting the upstream resource.
